<h1>Categorias</h1>
<table border="1" class="table table-striped table-hover" id="myTable">

    <thead>
    <tr>
        <th>id</th>
        <th>nombre</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($categorias as $p): ?>
        <tr>
            <td><?= $p->id ?></td>
            <td><a href="http://localhost:8080/Adelitas/categorias/show/<?= $p->id ?>"><?= $p->nombre ?></a>
                <?= Html::link("categorias/show/{$p->id}","Ir a categorias",["class"=>"btn btn-sm","title"=>"ir a categorias:"])?></td>

        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script>
    let table = new DataTable('#myTable', {
        // config options...
    });
</script>