<h1>Metodos Pago</h1>
<table class="table table-striped table-hover">

    <thead>
    <tr>
        <th>id</th>
        <th>nombre</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach ($metodos_pago as $p): ?>
        <tr>
            <td><?= $p->id ?></td>
            <td><a href="http://localhost:8080/Adelitas/metodos_pago/show/<?= $p->id ?>"><?= $p->nombre ?></a>
                <?= Html::link("metodos_pago/show/{$p->id}","Ir a Metodo Pago",["class"=>"btn btn-sm","title"=>"ir a Metodo pago:"])?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
